### ISSUE TITLE
How do i get the Kernel imgs

### ISSUE THREAD

**Issue by TIMESTICKING** [teboli/CPCR#1]
If I want to deblur my own pics, demo_real.py says a kernel img is  required.
and i dont understand what's the "training" for..
looking forward the replys, thank u

**Comment by teboli** [comment]
Hi! If you intend to restore your own pictures, you should provide a blur kernel k. In the demos, it is read from an .png or .jpg image that contains the support of the filter.
Also I am confused with the "training" thing.. Can you be more explicit about it? Thanks!
